add: docker.md
PerformanC/NodeLink pull request #57
Opened 2024-04-18 13:31 UTC by 1Lucas1apk

## Changes

creation of information on how to install NodeLink using docker

2024-04-18 13:39 UTC, ThePedroo requested changes
Will take a better look later, but I could catch some things that need change now

2024-04-18 13:39 UTC, ThePedroo commented on docs/docker.md
> +docker run -d --name nodelink -p 2333:2333 performanc/nodelink
`nodelink` -> `NodeLink` for the container name

2024-04-18 13:41 UTC, 1Lucas1apk commented on docs/docker.md
> +![past-file-config.js](https://i.ibb.co/k4BTgNW/image.png)
que diabos é dittos?

2024-04-18 13:42 UTC, ThePedroo commented on docs/docker.md
> +![past-file-config.js](https://i.ibb.co/k4BTgNW/image.png)
Ditto = "Aqui também" / "Duplicado"

2024-04-18 13:42 UTC, 1Lucas1apk commented on docs/docker.md
> +![terminal-command-line-sucess](https://i.ibb.co/xFbm28M/image.png)
não tenho os arquivos e não consigo baixa-los

2024-04-18 13:47 UTC, 1Lucas1apk commented on docs/docker.md
> +![past-file-config.js](https://i.ibb.co/k4BTgNW/image.png)
> Ditto = "Aqui também" / "Duplicado"

ainda não entendi
são imagens diferentes

2024-04-18 21:26 UTC, ThePedroo requested changes
Although it looks like a lot of things to change, it's actually few, just duplicated

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +![terminal-command-line-sucess](https://i.ibb.co/xFbm28M/image.png)
Just click in the image and "Save as xxx" then upload to GH

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +[Official Docker documentation] (https://docs.docker.com/engine/install/)
```suggestion
[Official Docker documentation](https://docs.docker.com/engine/install/)
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +[Docker-Compose] (https://docs.docker.com/compose/install/)
```suggestion
[Docker-Compose](https://docs.docker.com/compose/install/)
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +that's it, now just set it up on a client and be happy
```suggestion
That's it, now just set it up on a client and be happy.
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +an easier and quicker way is to use the Docker CLI
```suggestion
An easier and quicker way is to use the Docker CLI:
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +This way it's not very easy to modify the configuration file, but in the files inside the container you can find them in `usr/src/app`
```suggestion
This way it's not very easy to modify the configuration file, but it's localized in  `/usr/src/app`.
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +modifying the port where it exposes the NodeLink API is also the same as the first method `2333:5000` it will expose to localhost:5000
```suggestion
Modifying the port where it exposes the NodeLink API is also the same as the first method `2333:5000` it will expose to `localhost:5000`.
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +why is the first part still 2333:?
```suggestion
why is the first part still `2333:`?
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +this indicates the internal docker port where the API is running, if you modify in config.js, you also need to modify this internal port for example, you put 4444 in config.js you will put like this
```suggestion
This indicates the internal docker port where the API is running, if you modify in config.js, you also need to modify this internal port for example, you put `4444` in config.js you will put like this `4444:4444`.
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +docker run -d --name NodeLink -p 2333:2333 performanc/nodelink
```suggestion
# docker run -d --name NodeLink -p 2333:2333 performanc/nodelink
```

Doesn't docker require SU?

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +4. do whatever you want to change in config.js such as password, credentials or enable sources, finally open the terminal in the directory where these files are and type the following command: `docke
```suggestion
4. Do whatever any change you wish in config.js such as modifying the password, adding source credentials or enabling sources. Finally open the terminal in the directory where these files are located and type the following command: 

```shell
# docker compose up -d`
\`\`\` // Fix this because suggestions are broken

```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +3. with this, create a file in the same folder called config.js, and copy and paste the NodeLink configuration code into this file.
```suggestion
3. With this, create a file in the same folder called config.js, and copy and paste the NodeLink configuration code into this file.
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +2. once this is done, copy and paste this configuration:
```suggestion
2. Once it's done, copy and paste this configuration:
```

2024-04-18 21:26 UTC, ThePedroo commented on docs/docker.md
> +1. Create a folder wherever you want, inside this folder we'll create a file called docker-compose.yml
```suggestion
1. Create a folder wherever you want, inside this folder we'll create a file called `docker-compose.yml`
```

2024-04-19 00:56 UTC, 1Lucas1apk commented on docs/docker.md
> +docker run -d --name NodeLink -p 2333:2333 performanc/nodelink
não sei, mas no windows eu abro terminal normal mesmo

2024-04-19 01:21 UTC, 1Lucas1apk commented on docs/docker.md
> +docker run -d --name NodeLink -p 2333:2333 performanc/nodelink
precisa não

2024-04-19 19:32 UTC, 1Lucas1apk commented
..

2024-04-19 19:40 UTC, ThePedroo requested changes
Awesome! Just 2 things and it's good to go

2024-04-19 19:40 UTC, ThePedroo commented on README.md
> +### Or using Docker
```suggestion
### Using with Docker
```

2024-04-19 19:40 UTC, ThePedroo commented on README.md
> +for information on how to install NodeLink using Docker, see the documentation [docs/docker.md](docs/docker.md)
```suggestion
For information on how to install NodeLink using Docker, see [the NodeLink Docker guide](docs/docker.md).
```

2024-04-19 20:21 UTC, 1Lucas1apk commented
ready

2024-04-19 20:48 UTC, merged