Update: Using iOS client instead of Android to get YouTube video streams
PerformanC/NodeLink pull request #91
Opened 2024-12-03 01:28 UTC by 1Lucas1apk

## Changes

Using an iOS client instead of Android to obtain YouTube video streams, bypassing the errors that require you to log in, unrated videos, etc.

## Checkmarks

- [x] The modified endpoints have been tested.
- [x] Used the same indentation as the rest of the project.
- [x] Still compatible with LavaLink clients.

## Additional information

2024-12-10 02:25 UTC, ThePedroo requested changes
Please fix the indentation

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +        userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0'
```suggestion
        clientName: 'TVHTML5_SIMPLY_EMBEDDED_PLAYER',
        clientVersion: '2.0',
        userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0'
```

Do not change the indentation

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +      });
```suggestion
      })
```

Do not add semicolons

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +
Do not add spaces

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +
Do not add spaces

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +      console.log(playlist)
Don't add console.logs

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +
Do not add spaces

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +      });
```suggestion
      })
```


Do not add semicolons

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +
Do not add spaces

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +    });
```suggestion
    })
```

Do not add semicolons

2024-12-10 02:25 UTC, ThePedroo commented on src/sources/youtube.js
> +
Do not add spaces in empty lines

2024-12-10 17:46 UTC, ThePedroo requested changes

2024-12-10 17:46 UTC, ThePedroo commented on src/sources/youtube.js
> +    _switchClient(type === 'ytmusic' ? 'ANDROID_MUSIC' : 'IOS')
Don't remove the new line

2024-12-10 17:46 UTC, ThePedroo commented on src/sources/youtube.js
> +
Don't add a new line

2024-12-10 17:46 UTC, ThePedroo commented on src/sources/youtube.js
> -
Don't remove the line

2024-12-10 17:46 UTC, ThePedroo commented on src/sources/youtube.js
> -
Don't remove the line

2024-12-10 17:46 UTC, ThePedroo commented on src/sources/youtube.js
> -
Don't remove the line

2024-12-10 17:46 UTC, ThePedroo commented on src/sources/youtube.js
> -
Why is the error handling being removed?

2024-12-10 18:28 UTC, 1Lucas1apk commented
ready

2024-12-10 22:08 UTC, ThePedroo requested changes

2024-12-10 22:08 UTC, ThePedroo commented on src/sources/youtube.js
> +
No spaces in empty line

2024-12-10 22:08 UTC, ThePedroo commented on src/sources/youtube.js
> +
No spaces in empty line

2024-12-10 22:08 UTC, ThePedroo commented on src/sources/youtube.js
> +
No spaces in empty line

2024-12-10 22:08 UTC, ThePedroo commented on src/sources/youtube.js
> +
No spaces in empty line

2024-12-10 22:08 UTC, ThePedroo commented on src/sources/youtube.js
> -
Don't remove the line

2024-12-17 14:26 UTC, 1Lucas1apk commented
Only from Merge 🌝

2024-12-17 16:14 UTC, merged